name: App Updater

on: 
  push:
    branches:
      - main
  schedule: 
    - cron: '0 12 * * *' # 12 UTC 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: |
        cd api
        python api.py